version: '3'

services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    restart: always
    ports:
      - "80:80"  # Expose port 80 for HAProxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - haproxy_network

  web1:
    image: httpd:alpine
    container_name: web1
    restart: always
    networks:
      - haproxy_network

  web2:
    image: httpd:alpine
    container_name: web2
    restart: always
    networks:
      - haproxy_network

networks:
  haproxy_network:
    external: true
